module3/escamboapp/config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :send_mail, only: [:edit, :create]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'

end

module3/escamboapp/app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :member
  belongs_to :category
end

module3/escamboapp/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Constants
  ROLES = {:full_access => 0, :restricted_access => 1}

  # Enums
  enum role: ROLES

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # def self.with_full_access
  #   where(role: 'full_access')
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

module3/escamboapp/app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :description
end

module3/escamboapp/app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

module3/escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Pundit
  include Pundit

  # Manages Pundit Errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected

    def layout_by_resource
      if devise_controller? && resource_name == :admin
        "backoffice_devise"
      else
        "application"
      end
    end

    def user_not_authorized
      flash[:alert] = I18n.t('messages.not_authorized')
      redirect_to(request.referrer || root_path)
    end
end

module3/escamboapp/app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all
    #@admins = Admin.with_restricted_access
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: I18n.t('messages.created_with', item: @admin.name)
    else
      render :new
    end
  end

  def edit
    # Uses the before_action to set the admin.
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: I18n.t('messages.updated_with', item: @admin.name)
    else
      render :edit
    end
  end

  def destroy
    admin_name = @admin.name

    if @admin.destroy
      redirect_to backoffice_admins_path, notice: I18n.t('messages.destroyed_with', item: admin_name)
    else
      render :index
    end
  end

  private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      passwd = params[:admin][:password]
      passwd_confirmation = params[:admin][:password_confirmation]

      if passwd.blank? && passwd_confirmation.blank?
        params[:admin].except!(:password, :password_confirmation)
      end

      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
end

module3/escamboapp/app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)

    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: I18n.t('messages.created_with', item: @category.description)
    else
      render :new
    end
  end

  def edit
    # Uses before_action to set the category
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: I18n.t('messages.updated_with', item: @category.description)
    else
      render :edit
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end
end

module3/escamboapp/app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end
end

module3/escamboapp/app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
    # render app/views/backoffice/dashboard/index.html.erb
  end
end

module3/escamboapp/app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    AdminMailer.send_message(current_admin, params[:'recipient-name'], params[:'subject-text'], params[:'message-text']).deliver_now


    respond_to do |format|
      format.js
    end
  end
end

module3/escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
    current_admin # current_user to Pundit
  end
end

module3/escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"

  def index
    @categories = Category.all
  end
end

module3/escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
end

module3/escamboapp/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

module3/escamboapp/app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

module3/escamboapp/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

module3/escamboapp/app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

module3/escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

module3/escamboapp/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

module3/escamboapp/app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form",
           locals: {action_message: t('messages.editing', model: @admin.model_name.human)} %>

module3/escamboapp/app/views/backoffice/admins/index.html.erb
<h1 class="page-header"><%= @admins.model_name.human(count: 2) %></h1>

    <div class="panel panel-default">
        <div class="panel-heading">
            <%= t('messages.listing', model: @admins.model_name.human(count: 2)) %>

            <% if policy(@admins).new? %>
                <%= link_to new_backoffice_admin_path, class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
                    <i class="fa fa-plus"></i>
                <% end %>
            <% else %>
                <%= link_to '#', disabled: 'disabled', class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
                    <i class="fa fa-plus"></i>
                <% end %>
            <% end %>

        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th><%= @admins.model.human_attribute_name('name') %></th>
                            <th><%= @admins.model.human_attribute_name('role') %></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.role_i18n %></td>
                            <td style="width: 150px">
                               <%= link_to edit_backoffice_send_mail_path(admin), remote: true, class: "btn btn-info btn-circle" do %>
                                    <i class="fa fa-envelope"></i>
                                <% end %>

                                <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                                    <i class="fa fa-edit"></i>
                                <% end %>

                                <% if (current_admin.id != admin.id) && policy(@admins).destroy? %>
                                    <%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-danger btn-circle", data: {confirm: t('messages.confirm_with', item: admin.name )} do %>
                                        <i class="fa fa-minus"></i>
                                    <% end %>
                                <% else %>
                                    <%= link_to '#', disabled: 'disabled', class: "btn btn-danger btn-circle" do %>
                                        <i class="fa fa-minus"></i>
                                    <% end %>

                                <% end %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>


<%= render partial: "backoffice/admins/shared/send_mail" %>

module3/escamboapp/app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form",
           locals: {action_message: t('messages.new', model: @admin.model_name.human)} %>

module3/escamboapp/app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header"><%= @admin.model_name.human(count: 2) %></h1>

<% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

    <ul>
        <% @admin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>

    </div>
<% end %>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= action_message %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @admin]) do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class:"form-control", placeholder:"Nome do administrador" %>

                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class:"form-control", placeholder:"Email do administrador" %>

                </div>

                <% if policy(@admin).edit? %>
                    <div class="form-group">
                        <%= f.label :role %>
                        <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                            <div class="radio">
                                <%= b.label { b.radio_button + b.text} %>
                            </div>
                        <% end %>
                    </div>
                <% end %>

                <div class="form-group">
                    <%= f.label :password %>
                    <%= f.password_field :password, class:"form-control", placeholder:"Senha" %>

                </div>
                <div class="form-group">
                    <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da senha" %>

                </div>

                <button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>

module3/escamboapp/app/views/backoffice/admins/shared/_send_mail.html.erb
<!-- Modal -->
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
             <%= text_field_tag(:'recipient-name', nil, class: "form-control", readonly: 'readonly') %>
          </div>
         <div class="form-group">
            <label for="subject-text" class="col-form-label">Subject:</label>
            <%= text_field_tag(:'subject-text', nil, class: "form-control") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <%= text_area_tag(:'message-text', nil, class: "form-control") %>
          </div>
           <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= submit_tag 'Send Message', class: 'btn btn-primary' %>
      </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

module3/escamboapp/app/views/backoffice/categories/shared/_form.html.erb
<h1 class="page-header"><%= @category.model_name.human(count: 2) %></h1>

<% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

    <ul>
        <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>

    </div>
<% end %>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= action_message %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @category]) do |f| %>
                <div class="form-group">
                    <%= f.label :description %>
                    <%= f.text_field :description, class:"form-control", placeholder:"Ex: Animais/Pet" %>

                </div>
                <button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>

module3/escamboapp/app/views/backoffice/dashboard/index.html.erb
<h1 class="page-header">Dashboard</h1>

module3/escamboapp/app/views/backoffice/send_mail/create.js.erb
$(() => {
  const $modal = $('#sendMailModal').modal('hide')
  $.notify('Email enviado com sucesso!', 'success')
})

module3/escamboapp/app/views/backoffice/send_mail/edit.js.erb
$(() => {
  const $modal = $('#sendMailModal')
  $('#recipient-name').val('<%= @admin.email %>')
  $('#modalLabel').text('Enviar email para <%= @admin.name %>')
  $modal.modal()
  $modal.on('shown.bs.modal', () => {
    $('#subject-text').focus()
  })
})

module3/escamboapp/app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>