module1/notebook/config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :contacts
  resources :phones
  resources :addresses
  resources :kinds

end

module1/notebook/app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :kind
  has_one :address
  has_many :phones

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

   validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true
end

module1/notebook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]

  http_basic_authenticate_with name: "olavio", password: "cop", only: :destroy
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
    set_options_for_select
  end

  # GET /contacts/1/edit
  def edit
    set_options_for_select
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private

    def set_options_for_select
      @kind_options_for_select = Kind.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk,
      address_attributes: [:street, :city, :state],
      phones_attributes: [:id, :phone, :_destroy])
    end
end

module1/notebook/app/helpers/contacts_helper.rb
module ContactsHelper
end

module1/notebook/app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>


  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :kind_id %><br>
    <%= f.collection_select(:kind_id, @kind_options_for_select, :id, :description, {}, {class: "form-control"})%>
  </div>

    <%= f.fields_for :address do |address_fields| %>
      <div class="form-group">
        <%= address_fields.label :street %><br>
        <%= address_fields.text_field :street, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= address_fields.label :city %><br>
        <%= address_fields.text_field :city, class: "form-control" %>
        </div>
      <div class="form-group">
        <%= address_fields.label :state %><br>
        <%= address_fields.select(:state, options_for_states(@contact.address.state), {},  {class: "form-control"}) %>
      </div>
    <% end %>

     <div id="phones" class="form-group">

       <%= f.fields_for :phones do |phones_fields| %>
          <%= render partial: "phone_fields", locals: { f: phones_fields}  %>
       <% end %>

       <%= link_to_add_association('Adicionar Telefone', f, :phones, class: "btn btn-success") %>

     </div>

  <div class="form-group">
    <%= f.label :rmk %><br>
    <%= f.text_area :rmk, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= link_to 'Voltar', contacts_path, class: "btn btn-default" %>
    <%= f.submit button, class: "btn btn-primary" %>

  </div>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <!--#{pluralize(@contact.errors.count, "error")}-->
      <h2><%= " #{t('messages.errors')}:" %> </h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

module1/notebook/app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
    <div class="field">
      <div class="form-inline">
      <div class="form-group">
      <%= f.label :phone %><br>
      <%= f.text_field :phone, class: "form-control" %>
      <%= link_to_remove_association('remover', f, class: "btn btn-danger ") %>
      </div>
      </div>
    </div>
</div>

module1/notebook/app/views/contacts/edit.html.erb
    <h1 >Editar contato</h1>

    <%= render 'form', :button => t('buttons.update') %>

module1/notebook/app/views/contacts/index.html.erb
<script>
  $.notify("<%= notice %>", "success");
</script>

<h1 ><%= "#{t('messages.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}"%></h1>

<table class="table table-striped  table-hover">
  <thead>
    <tr>
      <th><%= @contacts.model.human_attribute_name("name") %></th>
      <th><%= @contacts.model.human_attribute_name("email") %></th>
      <th><%= @contacts.model.human_attribute_name("kind") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.kind.description %></td>
        <td><%= link_to t('buttons.edit'), edit_contact_path(contact), class: "btn btn-default" %></td>
        <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @contacts, :theme => 'twitter-bootstrap-3' %>
<br>

<%= link_to t('buttons.new'), new_contact_path, class: "btn btn-primary"%>
<%= link_to t('buttons.home'), root_path, class: "btn btn-success" %>

module1/notebook/app/views/contacts/new.html.erb
<div class="container">
    <h1 class="form-title">Novo contato</h1>

<%= render 'form', :button => t('buttons.create')  %>
</div>

module1/notebook/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>