module1/notebook/config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :contacts
  resources :phones
  resources :addresses
  resources :kinds

end

module1/notebook/app/models/kind.rb
class Kind < ActiveRecord::Base
    has_many :contacts
end

module1/notebook/app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kinds_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kinds_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

module1/notebook/app/helpers/kinds_helper.rb
module KindsHelper
end

module1/notebook/app/views/kinds/_form.html.erb
<%= form_for(@kind) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation" >
      <h2><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% @kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
     <%= link_to 'Voltar', contacts_path, class: "btn btn-default" %>
    <%= f.submit "Atualizar tipo", class: "btn btn-primary" %>
  </div>
<% end %>

module1/notebook/app/views/kinds/edit.html.erb
<h1>Editar Tipo</h1>

<%= render 'form' %>

module1/notebook/app/views/kinds/index.html.erb
<script>
  $.notify("<%= notice %>", "success");
</script>


<h1 ><%= "#{t('messages.listing')} #{@kinds.model.model_name.human(count: @kinds.count)}"%></h1>

<table class="table table-striped  table-hover">
  <thead>
    <tr>
      <th><%= @kinds.model.human_attribute_name("description") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to t('buttons.edit'), edit_kind_path(kind), class: "btn btn-default" %></td>
        <td><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: t('messages.confirm') }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('buttons.new'), new_kind_path, class: "btn btn-primary"%>
<%= link_to t('buttons.home'), root_path, class: "btn btn-success" %>

module1/notebook/app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form' %>

<%= link_to 'Back', kinds_path %>

module1/notebook/app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>